# Configuración para el entorno de Render
spring.datasource.url=jdbc:postgresql://dpg-d9uan09t0dsc73cvi07g-a:5432/clinica_db_vfp9
spring.datasource.username=clinica_user
spring.datasource.password=SpC7LCQoGxiRqErN46rNj4dMvG6Datpy
spring.datasource.driver-class-name=org.postgresql.Driver

# Deshabilitar validación de esquema (porque ya tienes las tablas en la BD)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true